name: teachr
favicon: null
layout_spectrum: 0.36316
typography_spectrum: 0.46971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dadfe5'
    - '#a6b6cd'
    - '#5f574c'
    - '#412b12'
    - '#e4bb79'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
