name: teachr
favicon: null
layout_spectrum: 0.45266
typography_spectrum: 0.32651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfff7'
    - '#5e83c5'
    - '#0c100f'
    - '#ab9973'
    - '#4e4438'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
