name: teachr
favicon: null
layout_spectrum: 0.80718
typography_spectrum: 0.87662
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dadfe5'
    - '#a6b6cd'
    - '#5f574c'
    - '#412b12'
    - '#e4bb79'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
