name: teachr
favicon: null
layout_spectrum: 0.45266
typography_spectrum: 0.32651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ececec'
    - '#000000'
    - '#888a7b'
    - '#7f313d'
    - '#e7c525'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
